### ISSUE TITLE
style props does not work in version 0.4.0.

### ISSUE THREAD

**Issue by NEONKID** [umidbekk/react-flag-kit#30]
```javascript
<FlagIcon code={country} size={20} style={{ margin: '.5em' }} />
```

In versions prior to 0.4.0, style props work normally, but in the latest version, style props do not seem to be applied.

**Comment by umidbekk** [comment]
@NEONKID Thanks for report! I finally had a reason to write some tests :) 

Released in https://github.com/umidbekk/react-flag-kit/releases/tag/v0.4.1
